Tumanov 12 done
eugene-okulik/ST7 pull request #121
Opened 2024-05-24 17:37 UTC by Viktor1-lab

2024-05-26 15:32 UTC, eugene-okulik requested changes

2024-05-26 15:32 UTC, eugene-okulik commented on homework/TumanovViktor/hw_12/home_12.py
> +    def __init__(self, autor, page, title, text, reserved, page_count, material):
> Какие-то из атрибутов будут общими для всех книг (материал, наличие текста), какие-то индивидуальными.

2024-05-26 15:32 UTC, eugene-okulik commented on homework/TumanovViktor/hw_12/home_12.py
> +        self.isbn = isbn
Получается, книги не Пушкина не имеют номера ISBN?

2024-05-26 15:32 UTC, eugene-okulik commented on homework/TumanovViktor/hw_12/home_12.py
> +        self.isbn = isbn
Ну и если ты сделал класс для книг Пушкина, то можно уже при создании не спрашивать автора
```python
def __init__(self, page, title, text, reserved, page_count, material, isbn):
    super().__init__('Pushkin', page, title, text, reserved, page_count, material)
```

2024-05-26 15:32 UTC, eugene-okulik commented on homework/TumanovViktor/hw_12/home_12.py
> +book5 = Book('Даль', 'Есть', 'Корабль', 'нет', False, 65, 'Бумага')
Книга без текста?

2024-05-26 15:55 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_12/home_12.py
> +book5 = Book('Даль', 'Есть', 'Корабль', 'нет', False, 65, 'Бумага')
Да там просто пустые листы  D^

2024-05-26 15:56 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_12/home_12.py
> +        self.isbn = isbn
Понял поправим

2024-05-26 18:47 UTC, Viktor1-lab commented
я начал переделывать вообще запутался и сделал просто как должно было быть, пока без фантазии

2024-05-27 14:38 UTC, eugene-okulik approved these changes

2024-05-27 14:38 UTC, eugene-okulik commented on homework/TumanovViktor/hw_12/home_12.py
> +
Если текст есть во всех книгах, то можно этот атрибут добавить вот здесь рядом с материалом и не нужно будет каждый раз при создании объекта True писать

2024-05-27 14:38 UTC, eugene-okulik commented on homework/TumanovViktor/hw_12/home_12.py
> +
А, и кстати, ты пишешь не True, а 'есть'. В программировании для всяких есть/нет, да/нет создан тип boolean и правильнее было бы пользоваться им.

2024-05-27 14:38 UTC, merged