dmitrii_homework_12_done
eugene-okulik/ST7 pull request #123
Opened 2024-05-25 12:26 UTC by Didroi

2024-05-27 06:47 UTC, eugene-okulik requested changes
Получается, ты подогнал родительский класс под дочерний класс. А если я создам еще подкласс книг для детей, и там будет какой-то атрибут, который я захочу распечатывать, то мне его нужно будет тоже добавить в родительский класс. Родительский класс вообще ничего не знает о существовании дочерних классов.  
Нужно или сделать два разных подхода к распечатыванию данных о книгах разных типов или реализовать это в классе каждой книги в методах с одинаковым названием.  
Второй подход - предпочтительнее.

2024-05-27 06:47 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_12/hometask.py
> +    school_subject = ''
У обычной книги нет школьного предмета, даже пустого

2024-05-27 06:47 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_12/hometask.py
> +def print_book_details(name):
Здесь в параметрах ты ждешь `name`, но ведь ты здесь ждешь объект книги, а не только название. Логичнее было бы назвать этот параметр `book`

2024-05-29 17:46 UTC, Didroi commented
исправил. вроде

2024-05-30 11:46 UTC, eugene-okulik approved these changes

2024-05-30 11:46 UTC, merged