Tumanov 13 done
eugene-okulik/ST7 pull request #133
Opened 2024-05-29 15:01 UTC by Viktor1-lab

2024-05-30 10:05 UTC, eugene-okulik requested changes
> Создать классы цветов: общий класс для всех цветов и классы для нескольких видов.

Общий класс для всех цветов ты сделал, но не сделал классы для нескольких видов.

2024-05-30 10:05 UTC, eugene-okulik commented on homework/TumanovViktor/hw_13/home_13.py
> +        self.tsvety.sort(key=lambda x: getattr(x, key))
:+1:

2024-05-30 10:33 UTC, Viktor1-lab commented
> > Создать классы цветов: общий класс для всех цветов и классы для нескольких видов.
> 
> Общий класс для всех цветов ты сделал, но не сделал классы для нескольких видов.

Я перед отправкой держал в голове что что то не хватает, и вот чего... переделаю

2024-05-31 10:16 UTC, eugene-okulik approved these changes

2024-05-31 10:16 UTC, eugene-okulik commented on homework/TumanovViktor/hw_13/home_13.py
> +        super().__init__(name, color, svezhest, lifespan, price, srok_zhizni)
У всех пионов названием будет Пион. И можно вомпользоваться тем, что для пиона есть отдельный дочерний класс и сделать так, чтобы при создании объекта пиона не приходилось писать его название.
```python
def __init__(self, color, svezhest, lifespan, price, srok_zhizni):
    super().__init__('Пион', color, svezhest, lifespan, price, srok_zhizni)
```

2024-05-31 10:16 UTC, merged