kate_hw_python_tools_completed
eugene-okulik/ST7 pull request #145
Opened 2024-06-02 17:37 UTC by KateHushcha

2024-06-07 11:56 UTC, eugene-okulik requested changes

2024-06-07 11:56 UTC, eugene-okulik commented on homework/kate_hushcha/hw_python_tools/eugene_file.py
> +file_path = 'C:\\Users\\kater\\ST7\\homework\\eugene_okulik\\hw_13\\data.txt'
У меня не работает )))

2024-06-11 00:51 UTC, KateHushcha commented on homework/kate_hushcha/hw_python_tools/eugene_file.py
> +file_path = 'C:\\Users\\kater\\ST7\\homework\\eugene_okulik\\hw_13\\data.txt'
Исправила

2024-06-11 11:32 UTC, eugene-okulik approved these changes

2024-06-11 11:32 UTC, merged