eduard:homework_14 done
eugene-okulik/ST7 pull request #148
Opened 2024-06-04 12:59 UTC by EduardYevdokiienko

2024-06-07 12:02 UTC, eugene-okulik requested changes

2024-06-07 12:02 UTC, eugene-okulik commented on homework/eduard_yevdokiienko/homework_14/task_2.py
> +            print(upper_word, end='')
Я пришел в твою папку homework_14, написал `python3 task_2.py`  - не работает.

2024-06-07 12:50 UTC, EduardYevdokiienko commented on homework/eduard_yevdokiienko/homework_14/task_2.py
> +            print(upper_word, end='')
Поправил

2024-06-10 12:05 UTC, eugene-okulik approved these changes

2024-06-10 12:05 UTC, merged