dmitrii_hm14_done
eugene-okulik/ST7 pull request #159
Opened 2024-06-08 18:00 UTC by Didroi

2024-06-11 09:09 UTC, eugene-okulik requested changes

2024-06-11 09:09 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_14/task2_reading_file.py
> +#  протестировать на линукс или маке не смог
Эмм. Я же минут 30 рассказывал про решение.

2024-06-11 09:09 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_14/task2_reading_file.py
> +#  протестировать на линукс или маке не смог
https://github.com/eugene-okulik/ST7/blob/main/homework/eugene_okulik/Lesson_14/file_path.py

2024-06-11 09:09 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_14/task2_reading_file.py
> +#  протестировать на линукс или маке не смог
Твое решение я как раз продемонстрировал как велосипед, который не нужно изобретать.

2024-06-11 09:09 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_14/task2_reading_file.py
> +#  протестировать на линукс или маке не смог
А вот здесь пример, который очень похож на то, что должно быть:
https://github.com/eugene-okulik/ST7/blob/main/homework/eugene_okulik/Lesson_14/alex_file.py

2024-06-12 18:04 UTC, Didroi commented on homework/dmitrii_kiselev/homework_14/task2_reading_file.py
> +#  протестировать на линукс или маке не смог
Сорри. Мой косяк. Был неправ. Исправился

2024-06-18 12:06 UTC, eugene-okulik approved these changes

2024-06-18 12:08 UTC, merged