dmitrii_hw15_done
eugene-okulik/ST7 pull request #160
Opened 2024-06-08 18:52 UTC by Didroi

2024-06-11 09:10 UTC, eugene-okulik requested changes

2024-06-11 09:10 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_15/single_task.py
> +sep = '/' if sys.platform in ['linux', 'darwin'] else '\\'
Здесь у тебя та же проблема, что в предыдущем. Ты попытался изобрести велосипед для того, что уже решено другими.

2024-06-12 18:09 UTC, Didroi commented on homework/dmitrii_kiselev/homework_15/single_task.py
> +sep = '/' if sys.platform in ['linux', 'darwin'] else '\\'
исправил

2024-06-18 12:09 UTC, eugene-okulik approved these changes

2024-06-18 12:09 UTC, merged