homework_16_17_done
eugene-okulik/ST7 pull request #171
Opened 2024-06-13 16:34 UTC by Didroi

Как оказалось, 16 и 17 задача в одной. Сорри)

2024-06-18 12:18 UTC, eugene-okulik requested changes
У тебя местами используются питоновские подстановки (`f'string'`) а местами защищенные (`%s`). В коде хорошо бы однообразие и лучше выбрать один подход и им пользоваться. И выбрать лучше защищенные подстановки.

2024-06-18 12:18 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_16_17/sql.py
> +    student_id_var = cursor.lastrowid
В задании было

>1. Создайте студента (student)
>2. Создайте несколько книг (books) и укажите, что ваш созданный студент взял их
>3. Создайте группу (group) и определите своего студента туда

У тебя выполнено:
1. Создайте группу
2. Создайте студента, проставив ему нужную группу.

2024-06-18 12:18 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_16_17/sql.py
> +    WHERE s.id = 80
а кто такой студент с id = 80 и почему мы всю программу добавляем одного студента, а потом информацию выводим по тому, у которого id = 80?

2024-07-08 07:39 UTC, eugene-okulik requested changes
Ок, где-то поменял питоновские подстановки на защищенные. Теперь осталось убрать хардкод айди и в правильном порядке выполнить задание.

2024-07-28 12:00 UTC, Didroi commented
Вроде исправил

2024-07-28 12:01 UTC, Didroi commented
По ошибке .env отправил(

2024-07-29 09:43 UTC, Didroi commented on homework/dmitrii_kiselev/homework_16_17/sql.py
> +    student_id_var = cursor.lastrowid
сделал

2024-07-29 14:36 UTC, eugene-okulik approved these changes

2024-07-29 14:36 UTC, merged