Tumanov 18 final
eugene-okulik/ST7 pull request #188
Opened 2024-06-20 08:29 UTC by Viktor1-lab

2024-06-20 10:28 UTC, eugene-okulik approved these changes

2024-06-20 10:28 UTC, eugene-okulik commented on homework/TumanovViktor/hw_18final/hw_final.py
> +                five_symb_after = min(len(line), word_index + len(args.word) + 5)
Был бы отличный вариант если бы в задании не было так:

> Также, программа должна вывести кусок строки, где был найден текст: 5 слов до найденного слова, найденное слово, 5 слов после найденного слова.

Ключевое в этой фразе - "слов" )))

2024-06-20 10:29 UTC, eugene-okulik requested changes
Случайно апрув нажал. Исправляюсь

2024-06-20 13:02 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_18final/hw_final.py
> +                five_symb_after = min(len(line), word_index + len(args.word) + 5)
замылился глаз

2024-06-21 15:02 UTC, eugene-okulik requested changes
Две проблемы:
1. Твоя программа ждет папку в параметре file_path, но работаешь ты с этим путем как будто тебе туда путь к файлу отдали. А тебе нужно произвести поиск по всем файлам папки, путь к которой тебе дали
2. Не ищет по части слова:
```
python hw_final.py ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.1.log --text SimpleDataFetcher
Слово не найдено
```

2024-06-24 08:39 UTC, eugene-okulik requested changes

2024-06-25 09:42 UTC, eugene-okulik approved these changes

2024-06-25 09:42 UTC, merged