Evgeny: homework 21 completed
eugene-okulik/ST7 pull request #204
Opened 2024-06-26 00:11 UTC by Dozer-Shit

2024-06-26 08:35 UTC, eugene-okulik requested changes
Start testing и Testing completed распечатывается перед и после каждого теста, а нужно чтобы перед запуском всех тестов распечатывалось "Start testing", а по завершении всех тестов - "Testing completed"

2024-06-26 08:35 UTC, eugene-okulik commented on homework/evgeny_shit/Homework_21/test_request.py
> +    assert delete_response.status_code == 200, f"Expected status code 200, got {delete_response.status_code}"
Этот ассерт ничего не будет проверять, так как тест свалится на delete_response.raise_for_status() если статус не 200. В тестах эта штука не используется. Я уже писал тебе об этом.

2024-06-26 08:35 UTC, eugene-okulik commented on homework/evgeny_shit/Homework_21/test_request.py
> +def create_delete_object():
Обычно фикстуру называют таким названием, из которого понятно что она возвращает. Эта возвращает object_id. Если ее так назвать, то и в тестах это будет выглядеть более понятно.

2024-06-26 08:35 UTC, eugene-okulik commented on homework/evgeny_shit/Homework_21/test_request.py
> +def create_object():
А чем отличается фикстура create_object от фикстуры create_delete_object?

2024-06-26 11:52 UTC, Dozer-Shit commented on homework/evgeny_shit/Homework_21/test_request.py
> +    assert delete_response.status_code == 200, f"Expected status code 200, got {delete_response.status_code}"
Я подумал это было на счет try блока
удалил райзы

2024-06-26 11:53 UTC, Dozer-Shit commented on homework/evgeny_shit/Homework_21/test_request.py
> +def create_delete_object():
Исправлено

2024-06-26 11:58 UTC, Dozer-Shit commented on homework/evgeny_shit/Homework_21/test_request.py
> +def create_object():
Скопировал и забыл исправить
Сделал ее только для теста с удалением чтобы не удалялось 2 раза

2024-06-26 11:59 UTC, Dozer-Shit commented
Все исправил, про Start testing и Testing completed - неправильно как-то прочитал ) Наоборот даже вывод подгонял, чтобы после каждого теста выводилось )

2024-06-27 06:06 UTC, eugene-okulik approved these changes

2024-06-27 06:07 UTC, merged