tumanov 21 done
eugene-okulik/ST7 pull request #205
Opened 2024-06-26 16:07 UTC by Viktor1-lab

2024-06-28 10:26 UTC, eugene-okulik requested changes
Старайся всегда давать названия, которые говорят правду. Это очень важно. Да, понятно, когда пишешь код, основной фокус направлен на то, чтобы его правильно написать. Но не забывай, что твой код будут читать другие и будут им пользоваться. Не усложняй им жизнь )))  

Ну и, если добавить в твои тесты еще и тест на удаление - вообще круто будет.

2024-06-28 10:26 UTC, eugene-okulik commented on homework/TumanovViktor/hw_21/test_pytest_hw.py
> +def publication_id():
А разве ты создаешь публикацию?

2024-06-28 10:26 UTC, eugene-okulik commented on homework/TumanovViktor/hw_21/test_pytest_hw.py
> +def test_publication_id():
Сложно протестиовать айди публикации в апишке, которая не работает с публикациями.

2024-06-28 10:52 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_21/test_pytest_hw.py
> +def publication_id():
имеется в виду я не написал криейт ?
т.к. в этой фикстуре создаётся публикация

2024-06-28 11:31 UTC, eugene-okulik commented on homework/TumanovViktor/hw_21/test_pytest_hw.py
> +def publication_id():
Имеется в виду, что исходя из названия, эта функция возвращает айди публикации. Но эта функция не возвращает айди публикации. Хорошо бы давать такие названия, которые соответствуют коду. В фиксутре не создается публикация.

2024-06-28 13:54 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_21/test_pytest_hw.py
> +def publication_id():
ага если всё правильно понял то переделал

2024-06-29 07:42 UTC, eugene-okulik requested changes
Тест на удаление всё еще просится быть добавленным ))))

2024-06-30 08:34 UTC, eugene-okulik approved these changes
:+1:

2024-06-30 08:34 UTC, merged