kate_hw_pytest_completed
eugene-okulik/ST7 pull request #207
Opened 2024-06-26 17:35 UTC by KateHushcha

2024-06-28 10:30 UTC, eugene-okulik requested changes
А если к тестам еще и добавить тест на удаление, тестам вообще цены не будет ))))

2024-06-28 10:30 UTC, eugene-okulik commented on homework/kate_hushcha/hw_pytest/test_all_in_pytest.py
> +    print(f'Created object {response.json()["id"]}')
Отлично, но не хватает какой-то проверки. Нужно, чтобы тест что-то тестировал. А для этого нужно какой-то ожидаемый результат сравнить с фактическим.

2024-06-28 16:46 UTC, KateHushcha commented on homework/kate_hushcha/hw_pytest/test_all_in_pytest.py
> +    print(f'Created object {response.json()["id"]}')
Исправила

2024-06-29 07:59 UTC, eugene-okulik approved these changes

2024-06-29 08:00 UTC, merged