dmitrii_hw_21_done
eugene-okulik/ST7 pull request #209
Opened 2024-06-26 19:10 UTC by Didroi

2024-06-28 10:29 UTC, eugene-okulik requested changes
Круто было бы добавить еще и тест на удаление.

2024-06-28 10:29 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_21/requirements.txt
Файл requirements обычно существует один в проекте. И он у нас в корне репозитория.

2024-06-28 10:29 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_21/test_api.py
> +def create_object():
Обычно фикстуре дают такое название, из которого понятно какие данные она возвращает. Здесь бы очень круто смотрелось название object_id и в тестах бы очень органично ложилось по смыслу.

2024-06-30 16:20 UTC, Didroi commented
Со всеми комментариями согласен. Исправился

2024-07-01 09:52 UTC, eugene-okulik requested changes

2024-07-04 08:04 UTC, eugene-okulik approved these changes

2024-07-04 08:04 UTC, merged