tumanov 24 done
eugene-okulik/ST7 pull request #236
Opened 2024-07-08 07:44 UTC by Viktor1-lab

2024-07-08 08:16 UTC, eugene-okulik requested changes
Выглядит неплохо, но есть некоторые вопросы. Возможно, их не будет когда появятся все файлы. Пока что, некоторые пустые, и, подозреваю, некоторые - неполные.

2024-07-08 11:10 UTC, Viktor1-lab commented
Да почему то не все отправились , пересоздал заново тогда добавились а сейчас линт не пропускает

2024-07-08 14:38 UTC, eugene-okulik commented
> Да почему то не все отправились , пересоздал заново тогда добавились а сейчас линт не пропускает

Так он и тогда не пропускал ))))

2024-07-08 14:40 UTC, eugene-okulik requested changes
ЧТо-то чуть чуть добавилось, но все еще очень много пустых файлов:  
base_api.py  
delete_obj.py  
get_id.py  
path_patchs.py  
schemas.py

2024-07-09 10:06 UTC, eugene-okulik reviewed
Всё выглядит отлично, но осталось избавиться от файла sql_with_python.py в этом пулл реквесте. Ну и избавиться от ошибок линта.

2024-07-10 07:31 UTC, closed without merging

2024-07-10 07:31 UTC, Viktor1-lab commented
...