eduard:API_homework_24 done
eugene-okulik/ST7 pull request #239
Opened 2024-07-09 12:12 UTC by EduardYevdokiienko

2024-07-09 16:43 UTC, EduardYevdokiienko commented
Я не понимаю в чем проблема, Pycharm все проверяю через Flake8 и никаких проблем не показывает.

2024-07-10 08:59 UTC, eugene-okulik approved these changes

2024-07-10 08:59 UTC, eugene-okulik commented on api_tests_yevdokiienko/conftest.py
> +    requests.delete(f'{url}/{object_id}')
Круто бы здесь тоже использовать те методы, которые ты сделал в классах.

2024-07-10 09:01 UTC, eugene-okulik requested changes
Осталось поправить ошибки линта

2024-07-10 09:01 UTC, eugene-okulik commented on api_tests_yevdokiienko/tests/test_objects_.py
> +)
Здесь у тебя отступ слишком большой. Пайчарм так делает.  
Вместо
```python
@pytest.mark.parametrize(
        'name', ['Apple MacBook Pro 16', 'APPLE MACBOOK PRO 16']
)
```
 должно быть
```python
@pytest.mark.parametrize(
    'name', ['Apple MacBook Pro 16', 'APPLE MACBOOK PRO 16']
)
```
Тогда линт будет спокоен

2024-07-11 09:21 UTC, eugene-okulik approved these changes

2024-07-11 09:21 UTC, merged