tumanov 29 done
eugene-okulik/ST7 pull request #255
Opened 2024-07-28 13:43 UTC by Viktor1-lab

2024-07-29 14:33 UTC, eugene-okulik requested changes

2024-07-29 14:33 UTC, eugene-okulik commented on homework/TumanovViktor/hw_29/homew_29_selenium.py
> +    sleep(1)
Во время выполнения всей этой штуки посмотри внимательно - после того как ты заполнил поле subject и идешь дальше что-то делать, поле subject остается незаполненным. Именно про это я говорил, когда говорил, что автотесты это тоже программа, которую нужно протестировать, что она действительно делает всё, что должна.

2024-07-29 15:58 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_29/homew_29_selenium.py
> +    sleep(1)
блин да, замылился уже глаз, всё верно оно пропадает

2024-07-30 12:17 UTC, eugene-okulik requested changes

2024-07-30 12:17 UTC, eugene-okulik commented on homework/TumanovViktor/hw_29/homew_29_selenium.py
> +    subject_container.click()
неа, не угадал. Пойди введи руками в это поле test text и нажми подсказку из автокомплита.

2024-07-30 16:24 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_29/homew_29_selenium.py
> +    subject_container.click()
на test text ничего не происходит, а вот сейчас начал ввод и после нажал enter и тогда уже добавился вариант предложенный

2024-07-31 08:06 UTC, eugene-okulik approved these changes

2024-07-31 08:06 UTC, merged