dmitrii_hw_30_selenium
eugene-okulik/ST7 pull request #275
Opened 2024-08-03 14:50 UTC by Didroi

2024-08-04 12:04 UTC, eugene-okulik requested changes

2024-08-04 12:04 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_30_selenium/test_selenium.py
> +    assert submitted_text.text == language_choice
Для работы с селектом в селениуме есть специальная штука, которую я показывал на занятии.

2024-08-04 13:43 UTC, Didroi commented on homework/dmitrii_kiselev/homework_30_selenium/test_selenium.py
> +    assert submitted_text.text == language_choice
исправил. Вообще, пересматривая твои уроки, нахожу много полезного, что не удержалось в голове сразу

2024-08-05 08:39 UTC, eugene-okulik approved these changes

2024-08-05 08:39 UTC, merged

2024-08-05 08:39 UTC, eugene-okulik commented on homework/dmitrii_kiselev/homework_30_selenium/test_selenium.py
> +    assert submitted_text.text == language_choice
Повторение - мать учения )))))))