tuman project done
eugene-okulik/ST7 pull request #302
Opened 2024-08-15 06:45 UTC by Viktor1-lab

2024-08-15 15:20 UTC, eugene-okulik requested changes
В целом, всё круто, но поправить бы то, на что линт ругается.

2024-08-15 15:20 UTC, eugene-okulik commented on ui_tests_tumanov/pages/create_new_account.py
> +        text_thank = wait.until(ec.visibility_of_element_located(loc.thank_message))
Можно было или в метод find добавить еще и проверку на visibility или сделать отдельный метод, который ищет и ждет visibility.

2024-08-15 15:20 UTC, eugene-okulik commented on ui_tests_tumanov/pages/create_new_account.py
> +        text_thank = wait.until(ec.visibility_of_element_located(loc.thank_message))
А ты вообще хоть где-то пользуешься методом find?

2024-08-15 16:29 UTC, Viktor1-lab commented on ui_tests_tumanov/pages/create_new_account.py
> +        text_thank = wait.until(ec.visibility_of_element_located(loc.thank_message))
нет(, добавлю в правках

2024-08-16 08:45 UTC, merged

2024-08-16 09:57 UTC, Viktor1-lab commented
та не, это я вчера отправил просто на проверку того что у меня всё нормально с гитом, я щас в процессе этого
добавления