tuman 34 done
eugene-okulik/ST7 pull request #303
Opened 2024-08-15 06:55 UTC by Viktor1-lab

2024-08-15 15:23 UTC, eugene-okulik requested changes

2024-08-15 15:23 UTC, eugene-okulik commented on homework/TumanovViktor/hw_34_pwr/hw_playwright.py
> +    assert first_name == 'Vitek'
В playwright не используются ассерты, все проверки делаются через `expect`

2024-08-15 15:23 UTC, eugene-okulik commented on homework/TumanovViktor/hw_34_pwr/hw_playwright.py
> +    assert first_name == 'Vitek'
Ну и проверить нужно было не содержимое поля формы, а содержимое таблички с результатами.

2024-08-15 15:23 UTC, eugene-okulik commented on homework/TumanovViktor/hw_34_pwr/hw_playwright.py
> +    assert first_name == 'Vitek'
А еще не вижу заполнения любимого поля subject.

2024-08-15 16:28 UTC, Viktor1-lab commented on homework/TumanovViktor/hw_34_pwr/hw_playwright.py
> +    assert first_name == 'Vitek'
поправлю

2024-08-16 08:48 UTC, eugene-okulik approved these changes

2024-08-16 08:48 UTC, eugene-okulik commented on homework/TumanovViktor/hw_34_pwr/hw_playwright.py
> +    expect(user_name).to_have_text('Vitek Tuman')
Если ты элемент нашел по тексту, то какой смысл в нем проверять текст? Ты же уже писал проекты по автоматизации и знаешь, что тестовые данные могут быть разными, а мот элементы на странице всегда одинаковые. Здесь правильнее было бы каким-нибудь икспасом найти элемент, в котором отображаются имя и фамилия и проверить, что текст этого элемента такой, как тебе нужен.

2024-08-16 08:48 UTC, merged