Dmitrii hw32 pom
eugene-okulik/ST7 pull request #307
Opened 2024-08-17 17:42 UTC by Didroi

Finaly
Not perfect, bit I'm done

2024-08-19 09:21 UTC, eugene-okulik requested changes
Всё круто, но СЛИП!  
Да, у тебя он явно используется просто, чтобы посмотреть, но кто-то и разбираться не будет. Увидит в импортах слип - и не будет смотреть на твою работу.

2024-08-19 09:21 UTC, eugene-okulik commented on test_ui_dmitrii/tests/test_luma.py
> +    sleep(3)
Слип - зло

2024-08-19 09:21 UTC, eugene-okulik commented on test_ui_dmitrii/pages/base_page.py
> +        self.find((By.XPATH, f'//button[@{button_selector}]')).click()
Раз ты сделал отдельный метод на нажатие кнопки, можно было здесь искать элемент с ожиданием пока элемент станет clickable. Это бы сделало тесты более стабильными

2024-08-20 18:41 UTC, Didroi commented on test_ui_dmitrii/pages/base_page.py
> +        self.find((By.XPATH, f'//button[@{button_selector}]')).click()
тут не понял. Зачем? Ведь файнд ждет. Предлагаешь не использовать файнд?

2024-08-20 18:42 UTC, Didroi commented on test_ui_dmitrii/tests/test_luma.py
> +    sleep(3)
согласен

2024-08-20 18:47 UTC, Didroi commented
Запушил исправленное. Но не понял, зачем нужно было с кнопкой так делать - это противоречит DRY - если можно переиспользовать код - надо переиспользовать. А поиск по локатору с ожиданием у нас уже реализовано, причем в том же классе даже

2024-08-21 09:08 UTC, eugene-okulik commented on test_ui_dmitrii/pages/base_page.py
> +        self.find((By.XPATH, f'//button[@{button_selector}]')).click()
> тут не понял. Зачем? Ведь файнд ждет. Предлагаешь не использовать файнд?

Для кнопки нам важно, что кнопка будет кликабл. Если сделать такой метод, который ждет кликабельности, то мы просто добавляем стабильности. Да, файнд дождался появления, а этот еще и дождется кликабельности на всякий случай. И переиспользование здесь никуда не девается, всё остается DRY
```python
def push_the_button(self, button_selector):
    button = self.find((By.XPATH, f'//button[@{button_selector}]'))
    WebDriverWait(self.driver, 10).until(ec.element_to_be_clickable(button))
    button.click()
```

2024-08-21 09:11 UTC, eugene-okulik approved these changes

2024-08-21 09:11 UTC, eugene-okulik commented on test_ui_dmitrii/pages/base_page.py
> +        button.click()
Но и так тоже можно. Но если переиспользовать файнд, то будет двойная защита.

2024-08-21 09:11 UTC, merged