tuman project pwr done
eugene-okulik/ST7 pull request #331
Opened 2024-08-28 17:50 UTC by Viktor1-lab

2024-08-31 15:30 UTC, Viktor1-lab commented on pw_tests_tuman/pages/base_page.py
> +        return True
Да соглашусь, так я ещё и не использую это нигде( удалил это

2024-08-31 15:30 UTC, Viktor1-lab commented on pw_tests_tuman/pages/base_page.py
> +        return True
Поправил

2024-08-31 15:33 UTC, Viktor1-lab commented on pw_tests_tuman/pages/base_page.py
> +        return locator
Я попытаюсь оспорить, в 42 строке я нахожу  первый  элемент на странице, который соответствует указанному селектору, а 43 строке я и делаю проверку его видимости.

2024-09-02 07:05 UTC, eugene-okulik commented on pw_tests_tuman/pages/base_page.py
> +        return locator
При выполнении практически любого действия плейрайт сам ждем пока элемент станет видимым: https://playwright.dev/python/docs/actionability

2024-09-02 07:08 UTC, eugene-okulik requested changes
Похоже, твои правки не долетели до гитхаба.

2024-09-02 07:08 UTC, eugene-okulik commented on pw_tests_tuman/pages/base_page.py
> +        return True
Так не удалил же )))

2024-09-02 07:08 UTC, eugene-okulik commented on pw_tests_tuman/pages/base_page.py
> +        return True
Такое чувство, что ты поправил, но не залил.

2024-09-02 16:00 UTC, Viktor1-lab commented on pw_tests_tuman/pages/base_page.py
> +        return True
я пока да не заливал , этоя больше для себя сто бы понимать что сделал

2024-09-03 11:49 UTC, Viktor1-lab commented
Не пойму я как побороть ожидание скрипта, супорт текст дождался дальше нахожу нужны мне текст и тест ложится, в остальном все комменты отработал

2024-09-04 14:34 UTC, eugene-okulik commented
> Не пойму я как побороть ожидание скрипта, супорт текст дождался дальше нахожу нужны мне текст и тест ложится, в остальном все комменты отработал

```python
def test_login(page: Page):
    page.goto('https://magento.softwaretestingboard.com/customer/account/create/', wait_until='domcontentloaded')
    expect(page.locator('body')).to_contain_text('Support This Project')
    field = page.locator('#firstname')
    field.click()
    field.press('Enter')
    time.sleep(5)
```

2024-09-06 09:14 UTC, eugene-okulik approved these changes

2024-09-06 09:14 UTC, merged