homework_5_done
eugene-okulik/ST7 pull request #37
Opened 2024-04-24 09:08 UTC by Didroi

homework_5_done

Мне кажетя в 4-м задании можно поизящнее сделать - но я не смог придумать

2024-04-25 13:47 UTC, eugene-okulik requested changes
Всё отлично, но проверочку на внимательность не прошел.  
Ну и в последнем: приспособь там join.

2024-04-25 13:47 UTC, eugene-okulik commented on homework/dmitrii_kiselev/Homework_5/task1.py
> +my_dict['list'].pop(1)  # надеюсь правильно понял про удаление второго элемента. Речь про человеческий второй
Угу, правильно

2024-04-25 13:47 UTC, eugene-okulik commented on homework/dmitrii_kiselev/Homework_5/task1.py
> +my_dict['dict']['i am a tuple'] = 'some value'
А вот здесь - нет )))  
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-04-25 13:47 UTC, eugene-okulik commented on homework/dmitrii_kiselev/Homework_5/task2.py
:+1:

2024-04-25 13:47 UTC, eugene-okulik commented on homework/dmitrii_kiselev/Homework_5/task4.py
join бы здесь смотрелся просто божественно.

2024-04-25 16:11 UTC, Didroi commented on homework/dmitrii_kiselev/Homework_5/task1.py
> +my_dict['dict']['i am a tuple'] = 'some value'
добавил 2 правки, запушил. Пока глаза к гиту не привыкли, поэтому непонятно, может какие-то еще замечания пропустил

2024-04-29 11:58 UTC, eugene-okulik approved these changes

2024-04-29 11:58 UTC, merged