Alex_ v homework5
eugene-okulik/ST7 pull request #38
Opened 2024-04-24 19:03 UTC by AlexAQA2023

Lesson 5 : Python basics

2024-04-29 11:53 UTC, eugene-okulik requested changes

2024-04-29 11:53 UTC, eugene-okulik commented on homework/alex_v/homework5/task5.2.py
> +print(int(operation_three[-2:]) + 10)
В примерах - варианты того, как может ответить программа. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.  
Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-04-29 11:53 UTC, eugene-okulik commented on homework/alex_v/homework5/task5.1.py
нет выполнения этого:
> Для того, что хранится под ключом ‘dict’:
> добавьте элемент с ключом ('i am a tuple',) и любым значением

2024-04-29 20:31 UTC, AlexAQA2023 commented on homework/alex_v/homework5/task5.2.py
> +print(int(operation_three[-2:]) + 10)
done

2024-04-29 20:32 UTC, AlexAQA2023 commented on homework/alex_v/homework5/task5.1.py
done

2024-05-01 09:45 UTC, eugene-okulik requested changes
Еще один моментик ))

2024-05-01 09:45 UTC, eugene-okulik commented on homework/alex_v/homework5/task5.1.py
> +my_dict['i am a tuple'] = 'code refactoring'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-05-09 11:03 UTC, eugene-okulik requested changes

2024-05-09 11:03 UTC, eugene-okulik commented on homework/alex_v/homework5/task5.1.py
> +my_dict['i am a tuple,'] = 'code refactoring'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple,' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-05-10 17:41 UTC, eugene-okulik approved these changes

2024-05-10 17:41 UTC, merged