kate_python_basics_3_cmpleted
eugene-okulik/ST7 pull request #39
Opened 2024-04-25 00:55 UTC by KateHushcha

2024-04-29 11:57 UTC, eugene-okulik requested changes

2024-04-29 11:57 UTC, eugene-okulik commented on homework/kate_hushcha/homework_python_basics_3/assignment_1.py
> +my_dict['dic']['flower'] = 'i am a tuple'
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

ключ у тебя 'flower', а значение 'i am a tuple'. А должно быть: ключ ('i am a tuple',) и значение - какое придев голову.

2024-04-29 11:57 UTC, eugene-okulik commented on homework/kate_hushcha/homework_python_basics_3/assignment_2.py
> +print(total_3)
В примерах - варианты того, как может ответить программа. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.  
Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-04-29 11:57 UTC, eugene-okulik commented on homework/kate_hushcha/homework_python_basics_3/assignment_3.py
> +name, last_name, city, phone, country = person
Достаточно было вот этой распаковки. ))

2024-04-30 00:37 UTC, KateHushcha commented on homework/kate_hushcha/homework_python_basics_3/assignment_1.py
> +my_dict['dic']['flower'] = 'i am a tuple'
Исправилаю

2024-04-30 00:37 UTC, KateHushcha commented on homework/kate_hushcha/homework_python_basics_3/assignment_2.py
> +print(total_3)
Вроде получилось исправить.

2024-05-01 09:50 UTC, eugene-okulik requested changes

2024-05-01 09:50 UTC, eugene-okulik commented on homework/kate_hushcha/homework_python_basics_3/assignment_1.py
> +my_dict['dic']['i am a tuple'] = 'therefore i am a flower called tulip'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-05-01 09:50 UTC, eugene-okulik commented on homework/kate_hushcha/homework_python_basics_3/assignment_2.py
> +print(total_3)
Решение этой задачки через сплит - самое оптимальное. Но, в задании сказано решить через index и срезы. А сейчас у тебя ни того ни другого )))

2024-05-01 22:28 UTC, KateHushcha commented on homework/kate_hushcha/homework_python_basics_3/assignment_1.py
> +my_dict['dic']['i am a tuple'] = 'therefore i am a flower called tulip'
Хитренькая задачка) Спасибо!

2024-05-01 22:29 UTC, KateHushcha commented on homework/kate_hushcha/homework_python_basics_3/assignment_2.py
> +print(total_3)
Я зашла в тупик. Понимаю, что общее у них то, что числа идут последние или что после двоеточия, но никак не пойму как это сделать и с помощью среза и с помощью index.

2024-05-02 23:13 UTC, KateHushcha commented on homework/kate_hushcha/homework_python_basics_3/assignment_2.py
> +print(total_3)
Исправила.

2024-05-09 09:29 UTC, eugene-okulik approved these changes

2024-05-09 09:29 UTC, merged