elena_maskevich_hw5
eugene-okulik/ST7 pull request #41
Opened 2024-04-25 17:15 UTC by ElenaMaskevich

2024-04-29 12:01 UTC, eugene-okulik requested changes

2024-04-29 12:01 UTC, eugene-okulik commented on homework/elena_maskevich/homework_5/task1.py
> +print(my_tuple[4])
Это ты вывела пятый элемент списка. А нужно последний. Если по какой-то причине в этом кортеже окажется 6 элементов, то этим кодом последний не распечатается.

2024-04-29 12:01 UTC, eugene-okulik commented on homework/elena_maskevich/homework_5/task1.py
> +my_dict1['i am a tuple'] = 'tuple'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-04-29 12:01 UTC, eugene-okulik commented on homework/elena_maskevich/homework_5/task2.py
> +third_number = int(third_line[(third_index + 2):]) + 10
:+1:

2024-04-29 15:50 UTC, ElenaMaskevich commented on homework/elena_maskevich/homework_5/task1.py
> +print(my_tuple[4])
Поправила

2024-04-29 15:50 UTC, ElenaMaskevich commented on homework/elena_maskevich/homework_5/task1.py
> +my_dict1['i am a tuple'] = 'tuple'
Поправила

2024-05-01 09:38 UTC, eugene-okulik approved these changes

2024-05-01 09:38 UTC, merged