done hw6
eugene-okulik/ST7 pull request #45
Opened 2024-04-27 09:45 UTC by ElenaMaskevich

2024-04-30 10:19 UTC, eugene-okulik requested changes

2024-04-30 10:19 UTC, eugene-okulik commented on homework/elena_maskevich/homework_6/task_1.py
Прикольно. Ты первая, кто так сделал. И это странно. Ведь в задании действительно не указано с какой стороны нужно добавить этот инг )))  
Но в начало - сильно просто. Добавь в конец каждого слова.

2024-05-01 04:07 UTC, ElenaMaskevich commented on homework/elena_maskevich/homework_6/task_1.py
забавно) даже не подумала, чтобы в конец добавлять, но было сомнение, что легко только)
поправила

2024-05-02 14:59 UTC, eugene-okulik approved these changes

2024-05-02 14:59 UTC, merged