kate_hw_6_completed
eugene-okulik/ST7 pull request #57
Opened 2024-04-30 00:35 UTC by KateHushcha

2024-05-01 09:47 UTC, eugene-okulik requested changes

2024-05-01 09:47 UTC, eugene-okulik commented on homework/kate_hushcha/homework_6/assignment_1.py
> +text_2 = 'Integer urna nisl, facilisis vitae semper at, dignissim vitae libero'
А с какой целью ты один текст разделила на два?

2024-05-01 10:37 UTC, KateHushcha commented on homework/kate_hushcha/homework_6/assignment_1.py
> +text_2 = 'Integer urna nisl, facilisis vitae semper at, dignissim vitae libero'
Я решила, что так будет удобнее)
Сейчас исправлю.

2024-05-02 15:05 UTC, eugene-okulik approved these changes

2024-05-02 15:05 UTC, merged